# Generated by Django 2.2.7 on 2019-11-20 14:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shortcut', models.CharField(max_length=2)),
                ('lastVisit', models.DateTimeField(default=datetime.datetime(2019, 11, 20, 15, 30, 42, 819816))),
                ('lastFloor', models.DecimalField(decimal_places=0, default=14, max_digits=2)),
                ('lastUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfVisit', models.DateTimeField(auto_now=True)),
                ('floor', models.DecimalField(decimal_places=0, max_digits=2)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
