# Generated by Django 2.2.7 on 2019-11-20 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='lastFloor',
            field=models.DecimalField(decimal_places=0, default=13, max_digits=2),
        ),
        migrations.AlterField(
            model_name='provider',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 15, 35, 3, 166805)),
        ),
    ]
