# Generated by Django 2.2.7 on 2019-11-25 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191120_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 16, 22, 49, 684637)),
        ),
    ]
