# Generated by Django 2.2.7 on 2019-11-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191125_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='provider',
            name='lastFloor',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='lastUser',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='lastVisit',
        ),
        migrations.AddField(
            model_name='provider',
            name='logo',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
