# Generated by Django 2.2.7 on 2019-11-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191126_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='shortcut',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
